// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lexico.jflex

/*primer seccion: codigo java que se copiara arriba*/
package com.cunoc.JFlex_Cup.Json;


import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;
import com.cunoc.JFlex_Cup.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LexicoJson implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\6\1\22\0\1\1\1\2\1\3\1\4\4\2"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\2\1\13"+
    "\12\14\1\15\2\2\1\0\3\2\1\16\1\17\1\20"+
    "\4\21\1\22\1\23\1\21\1\24\1\25\5\21\1\26"+
    "\5\21\1\27\1\30\1\21\1\31\1\2\1\32\1\2"+
    "\1\33\1\2\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\21\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\21\1\53\1\54\1\55\1\56\1\21"+
    "\1\57\1\60\1\61\1\21\1\62\1\63\1\64\1\2"+
    "\6\0\1\1\32\0\1\1\u01df\0\1\1\177\0\13\1"+
    "\35\0\2\1\5\0\1\1\57\0\1\1\240\0\1\1"+
    "\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\2\1\20\1\1\3\0\1\1\33\0\1\21"+
    "\1\0\1\22\24\0\1\23\22\0\1\24\5\0\1\25"+
    "\2\0\1\26\1\0\1\27\1\30\1\31\1\0\1\32"+
    "\3\0\1\33\1\34\2\0\1\35\6\0\1\36\5\0"+
    "\1\37\1\0\1\40\4\0\1\41\7\0\1\42\10\0"+
    "\1\43\10\0\1\44\4\0\1\45\4\0\1\46\1\47"+
    "\6\0\1\50\3\0\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\65\0\65\0\65"+
    "\0\65\0\65\0\65\0\65\0\u0109\0\65\0\237\0\237"+
    "\0\237\0\u013e\0\237\0\u0173\0\u01a8\0\u01dd\0\u0212\0\u0247"+
    "\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef"+
    "\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597"+
    "\0\u05cc\0\u0601\0\u0636\0\u066b\0\u06a0\0\u06d5\0\u070a\0\u073f"+
    "\0\u0774\0\u07a9\0\u07de\0\65\0\u0813\0\65\0\u0848\0\u087d"+
    "\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25"+
    "\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd"+
    "\0\u0c02\0\u0c37\0\65\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40"+
    "\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8"+
    "\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\65\0\u1026\0\u105b"+
    "\0\u1090\0\u10c5\0\u10fa\0\65\0\u112f\0\u1164\0\65\0\u1199"+
    "\0\65\0\65\0\65\0\u11ce\0\65\0\u1203\0\u1238\0\u126d"+
    "\0\65\0\65\0\u12a2\0\u12d7\0\65\0\u130c\0\u1341\0\u1376"+
    "\0\u13ab\0\u13e0\0\u1415\0\65\0\u144a\0\u147f\0\u14b4\0\u14e9"+
    "\0\u151e\0\65\0\u1553\0\65\0\u1588\0\u15bd\0\u15f2\0\u1627"+
    "\0\65\0\u165c\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u1765\0\u179a"+
    "\0\65\0\u17cf\0\u1804\0\u1839\0\u186e\0\u18a3\0\u18d8\0\u190d"+
    "\0\u1942\0\65\0\u1977\0\u19ac\0\u19e1\0\u1a16\0\u1a4b\0\u1a80"+
    "\0\u1ab5\0\u1aea\0\65\0\u1b1f\0\u1b54\0\u1b89\0\u1bbe\0\65"+
    "\0\u1bf3\0\u1c28\0\u1c5d\0\u1c92\0\65\0\65\0\u1cc7\0\u1cfc"+
    "\0\u1d31\0\u1d66\0\u1d9b\0\u1dd0\0\65\0\u1e05\0\u1e3a\0\u1e6f"+
    "\0\65";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\4\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\13\2\1\17"+
    "\1\20\1\4\26\2\1\21\1\22\1\23\66\0\1\3"+
    "\61\0\1\3\3\0\3\4\24\0\3\4\26\0\3\4"+
    "\2\0\2\4\1\24\11\0\1\25\1\26\2\25\1\27"+
    "\6\25\2\4\1\30\1\31\1\32\1\33\4\25\1\34"+
    "\4\25\1\35\1\25\1\36\1\37\1\25\1\40\1\41"+
    "\1\42\2\25\3\4\14\0\1\15\51\0\1\3\3\4"+
    "\24\0\3\4\26\0\1\4\1\22\1\4\2\0\3\4"+
    "\7\0\1\43\1\0\13\43\3\4\26\43\3\4\16\0"+
    "\13\44\3\0\26\44\21\0\10\44\1\45\2\44\3\0"+
    "\26\44\21\0\1\46\12\44\3\0\26\44\5\0\3\4"+
    "\11\0\13\44\3\4\26\44\3\4\16\0\13\44\3\0"+
    "\12\44\1\47\13\44\21\0\13\44\3\0\15\44\1\50"+
    "\1\44\1\51\6\44\21\0\13\44\3\0\15\44\1\52"+
    "\10\44\21\0\13\44\3\0\1\53\25\44\21\0\13\44"+
    "\3\0\1\54\25\44\21\0\13\44\3\0\12\44\1\55"+
    "\2\44\1\56\10\44\21\0\13\44\3\0\15\44\1\57"+
    "\10\44\21\0\13\44\3\0\1\60\24\44\1\61\21\0"+
    "\13\44\3\0\14\44\1\62\11\44\21\0\13\44\3\0"+
    "\15\44\1\63\10\44\6\0\1\64\10\0\1\65\1\0"+
    "\13\65\3\0\26\65\6\0\1\66\10\0\1\44\1\0"+
    "\13\44\3\0\26\44\6\0\1\66\10\0\1\44\1\0"+
    "\5\44\1\67\5\44\3\0\26\44\6\0\1\66\10\0"+
    "\1\44\1\0\7\44\1\70\3\44\3\0\26\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\12\44\1\71"+
    "\13\44\6\0\1\66\10\0\1\44\1\0\13\44\3\0"+
    "\1\72\23\44\1\73\1\44\6\0\1\66\10\0\1\44"+
    "\1\0\13\44\3\0\10\44\1\74\15\44\6\0\1\66"+
    "\10\0\1\44\1\0\13\44\3\0\12\44\1\75\1\44"+
    "\1\76\11\44\6\0\1\66\10\0\1\44\1\0\13\44"+
    "\3\0\12\44\1\77\13\44\6\0\1\66\10\0\1\44"+
    "\1\0\13\44\3\0\13\44\1\100\12\44\6\0\1\66"+
    "\10\0\1\44\1\0\13\44\3\0\1\101\25\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\20\44\1\102"+
    "\5\44\6\0\1\66\10\0\1\44\1\0\13\44\3\0"+
    "\23\44\1\103\2\44\6\0\1\66\10\0\1\44\1\0"+
    "\13\44\3\0\17\44\1\104\6\44\6\0\1\66\10\0"+
    "\1\44\1\0\13\44\3\0\16\44\1\105\7\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\3\44\1\106"+
    "\22\44\6\0\1\66\10\0\1\44\1\0\13\44\3\0"+
    "\17\44\1\107\6\44\6\0\1\64\10\0\1\110\1\0"+
    "\13\110\3\0\26\110\6\0\1\66\10\0\1\44\1\0"+
    "\2\44\1\111\10\44\3\0\26\44\6\0\1\66\10\0"+
    "\1\44\1\0\7\44\1\112\3\44\3\0\26\44\6\0"+
    "\1\113\10\0\1\44\1\0\13\44\3\0\26\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\17\44\1\114"+
    "\6\44\6\0\1\66\10\0\1\44\1\0\13\44\2\0"+
    "\1\115\4\44\1\116\21\44\6\0\1\66\10\0\1\44"+
    "\1\0\13\44\3\0\2\44\1\117\23\44\6\0\1\66"+
    "\10\0\1\44\1\0\13\44\3\0\20\44\1\120\5\44"+
    "\6\0\1\66\10\0\1\44\1\0\13\44\3\0\5\44"+
    "\1\121\20\44\6\0\1\66\10\0\1\44\1\0\13\44"+
    "\3\0\12\44\1\122\13\44\6\0\1\66\10\0\1\44"+
    "\1\0\13\44\3\0\4\44\1\123\21\44\6\0\1\66"+
    "\10\0\1\44\1\0\13\44\3\0\25\44\1\124\6\0"+
    "\1\66\10\0\1\44\1\0\11\44\1\125\1\126\3\0"+
    "\26\44\6\0\1\66\10\0\1\44\1\0\13\44\3\0"+
    "\20\44\1\127\5\44\6\0\1\66\10\0\1\44\1\0"+
    "\13\44\3\0\6\44\1\130\17\44\6\0\1\66\10\0"+
    "\1\44\1\0\13\44\3\0\4\44\1\131\21\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\4\44\1\132"+
    "\21\44\6\0\1\66\10\0\1\44\1\0\13\44\3\0"+
    "\12\44\1\133\13\44\6\0\1\64\10\0\1\134\1\0"+
    "\13\134\3\0\26\134\6\0\1\66\10\0\1\44\1\0"+
    "\6\44\1\135\4\44\3\0\26\44\6\0\1\136\10\0"+
    "\1\44\1\0\13\44\3\0\26\44\6\0\1\66\10\0"+
    "\1\44\1\0\13\44\3\0\3\44\1\137\22\44\41\0"+
    "\1\140\12\0\1\141\16\0\1\66\10\0\1\44\1\0"+
    "\13\44\3\0\20\44\1\142\5\44\6\0\1\66\10\0"+
    "\1\44\1\0\13\44\3\0\11\44\1\143\14\44\6\0"+
    "\1\144\10\0\1\44\1\0\13\44\3\0\26\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\10\44\1\145"+
    "\15\44\6\0\1\66\10\0\1\44\1\0\13\44\2\0"+
    "\1\146\26\44\6\0\1\147\10\0\1\44\1\0\13\44"+
    "\3\0\26\44\6\0\1\66\10\0\1\44\1\0\13\44"+
    "\3\0\4\44\1\150\21\44\6\0\1\151\10\0\1\44"+
    "\1\0\13\44\3\0\26\44\6\0\1\152\10\0\1\44"+
    "\1\0\13\44\3\0\26\44\6\0\1\153\10\0\1\44"+
    "\1\0\13\44\3\0\26\44\6\0\1\66\10\0\1\44"+
    "\1\0\13\44\3\0\4\44\1\154\21\44\6\0\1\155"+
    "\10\0\1\44\1\0\13\44\3\0\26\44\6\0\1\66"+
    "\10\0\1\44\1\0\13\44\3\0\5\44\1\156\20\44"+
    "\6\0\1\66\10\0\1\44\1\0\13\44\3\0\3\44"+
    "\1\157\22\44\6\0\1\64\10\0\1\160\1\0\13\160"+
    "\3\0\26\160\6\0\1\161\10\0\1\44\1\0\13\44"+
    "\3\0\26\44\6\0\1\162\10\0\1\44\1\0\13\44"+
    "\3\0\26\44\54\0\1\163\63\0\1\164\17\0\1\165"+
    "\10\0\1\44\1\0\13\44\3\0\26\44\6\0\1\66"+
    "\10\0\1\44\1\0\13\44\2\0\1\166\26\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\6\44\1\167"+
    "\17\44\41\0\1\170\31\0\1\66\10\0\1\44\1\0"+
    "\13\44\3\0\17\44\1\171\6\44\6\0\1\66\10\0"+
    "\1\44\1\0\13\44\3\0\21\44\1\172\4\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\10\44\1\173"+
    "\15\44\6\0\1\174\10\0\1\44\1\0\13\44\3\0"+
    "\20\44\1\175\5\44\6\0\1\64\10\0\1\176\1\0"+
    "\13\176\3\0\26\176\51\0\1\177\51\0\1\200\67\0"+
    "\1\201\31\0\1\202\10\0\1\44\1\0\13\44\3\0"+
    "\26\44\54\0\1\203\16\0\1\204\10\0\1\44\1\0"+
    "\13\44\2\0\1\205\26\44\6\0\1\66\10\0\1\44"+
    "\1\0\13\44\2\0\1\206\20\44\1\207\5\44\6\0"+
    "\1\66\10\0\1\44\1\0\13\44\3\0\14\44\1\210"+
    "\11\44\6\0\1\211\10\0\1\44\1\0\13\44\3\0"+
    "\26\44\6\0\1\64\10\0\1\212\1\0\13\212\3\0"+
    "\26\212\54\0\1\213\70\0\1\214\60\0\1\215\61\0"+
    "\1\216\54\0\1\217\64\0\1\220\31\0\1\221\10\0"+
    "\1\44\1\0\13\44\3\0\26\44\6\0\1\66\10\0"+
    "\1\44\1\0\13\44\3\0\4\44\1\222\21\44\6\0"+
    "\1\64\134\0\1\223\45\0\1\224\76\0\1\225\67\0"+
    "\1\226\64\0\1\227\64\0\1\230\16\0\1\66\10\0"+
    "\1\44\1\0\13\44\3\0\3\44\1\231\22\44\6\0"+
    "\1\232\134\0\1\233\62\0\1\234\66\0\1\235\57\0"+
    "\1\236\64\0\1\237\21\0\1\66\10\0\1\44\1\0"+
    "\13\44\2\0\1\240\26\44\45\0\1\241\75\0\1\242"+
    "\14\0\1\243\132\0\1\244\64\0\1\245\51\0\1\246"+
    "\66\0\1\247\27\0\1\250\134\0\1\251\64\0\1\252"+
    "\62\0\1\253\70\0\1\254\12\0\1\255\64\0\1\256"+
    "\127\0\1\257\51\0\1\260\102\0\1\261\51\0\1\262"+
    "\101\0\1\263\62\0\1\264\16\0\1\265\127\0\1\266"+
    "\67\0\1\267\66\0\1\270\14\0\1\271\61\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7844];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\7\11\1\1\1\11\6\1\3\0"+
    "\1\1\33\0\1\11\1\0\1\11\24\0\1\11\22\0"+
    "\1\11\5\0\1\11\2\0\1\11\1\0\3\11\1\0"+
    "\1\11\3\0\2\11\2\0\1\11\6\0\1\11\5\0"+
    "\1\11\1\0\1\11\4\0\1\11\7\0\1\11\10\0"+
    "\1\11\10\0\1\11\4\0\1\11\4\0\2\11\6\0"+
    "\1\11\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[185];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private  List<Token> listComments =  new ArrayList<>();
    private String report = "";
    private void addComments(){
        listComments.add(new Token((yyline+1),(yycolumn+1),yytext()));
    }
    private void print(String token){
        //Console.ConsoleText.append("\n<linea:"+(yyline+1)+"><colum:"+(yycolumn+1)+"><TOKEN:"+yytext()+">");
        //report+="\n<linea:"+(yyline+1)+"><colum:"+(yycolumn+1)+"><TOKEN:"+yytext()+">";
    }
    public String getReport(){
        return this.report;
    }
    public void setReport(String repor){
        this.report = repor;
    }
    
    public List<Token>  getlistComments(){
        return this.listComments;
    };


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoJson(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { print((yytext()));
            }
            // fall through
          case 42: break;
          case 2:
            { /*ESPACIOS*/
            }
            // fall through
          case 43: break;
          case 3:
            { print("\"");return new Symbol(sym.COMILLAS,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 44: break;
          case 4:
            { print("(");return new Symbol(sym.P_APERTURA,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 45: break;
          case 5:
            { print(")");return new Symbol(sym.P_CIERRE,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 46: break;
          case 6:
            { print("*");return new Symbol(sym.MULTIPLICAR,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 47: break;
          case 7:
            { print("+");return new Symbol(sym.SUMAR,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 48: break;
          case 8:
            { print(",");return new Symbol(sym.COMA,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 49: break;
          case 9:
            { print("-");return new Symbol(sym.RESTAR,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 50: break;
          case 10:
            { print("/");return new Symbol(sym.DIVIDIR,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 51: break;
          case 11:
            { print("{NUMERO}" );return new Symbol(sym.ENTERO,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 52: break;
          case 12:
            { print(":");return new Symbol(sym.DOBLE_PUNTO,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 53: break;
          case 13:
            { print("[");return new Symbol(sym.C_APERTURA,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 54: break;
          case 14:
            { print("]");return new Symbol(sym.C_CIERRE,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 55: break;
          case 15:
            { print("{");return new Symbol(sym.L_APERTURA,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 56: break;
          case 16:
            { print("}");return new Symbol(sym.L_CIERRE,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 57: break;
          case 17:
            { print(yytext() );return new Symbol(sym.COLOR,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 58: break;
          case 18:
            { print("{CARACTER}" );return new Symbol(sym.CARACTER,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 59: break;
          case 19:
            { print("all"                        );return new Symbol(sym.ALL   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 60: break;
          case 20:
            { print("HALL"                       );return new Symbol(sym.HALL   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 61: break;
          case 21:
            { print("cols"                       );return new Symbol(sym.COLS   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 62: break;
          case 22:
            { print("name"                       );return new Symbol(sym.NAME   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 63: break;
          case 23:
            { print("posX"                       );return new Symbol(sym.POSX   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 64: break;
          case 24:
            { print("posY"                       );return new Symbol(sym.POSY   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 65: break;
          case 25:
            { print("rows"                       );return new Symbol(sym.ROWS   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 66: break;
          case 26:
            { print("type"                       );return new Symbol(sym.TYPE   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 67: break;
          case 27:
            { print("BRICK"                       );return new Symbol(sym.BRICK   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 68: break;
          case 28:
            { print("board"                      );return new Symbol(sym.BOARD   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 69: break;
          case 29:
            { print("boxes"                      );return new Symbol(sym.BOXES   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 70: break;
          case 30:
            { print("world"                      );return new Symbol(sym.WORLD   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 71: break;
          case 31:
            { print("config"                     );return new Symbol(sym.COFIG   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 72: break;
          case 32:
            { print("player"                     );return new Symbol(sym.PLAYER   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 73: break;
          case 33:
            { print("worlds"                     );return new Symbol(sym.WORLDS   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 74: break;
          case 34:
            { print("targets"                    );return new Symbol(sym.TARGETS   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 75: break;
          case 35:
            { print("box_color"                  );return new Symbol(sym.BOX_COLOR   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 76: break;
          case 36:
            { print("hall_color"                 );return new Symbol(sym.HALL_COLOR   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 77: break;
          case 37:
            { print("brick_color"                );return new Symbol(sym.BRICK_COLOR   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 78: break;
          case 38:
            { print("player_color"               );return new Symbol(sym.PLAYER_COLOR   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 79: break;
          case 39:
            { print("target_color"               );return new Symbol(sym.TAGET_COLOR   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 80: break;
          case 40:
            { print("undefined_color"            );return new Symbol(sym.UNDEFINED_COLOR   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 81: break;
          case 41:
            { print("box_on_target_color"        );return new Symbol(sym.BOX_ON_COLOR   ,yyline,yycolumn, (yytext()));
            }
            // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
