
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.JFlex_Cup.Json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C_APERTURA = 31;
  public static final int MULTIPLICAR = 26;
  public static final int BRICK_COLOR = 9;
  public static final int WORLDS = 36;
  public static final int DOBLE_PUNTO = 20;
  public static final int L_CIERRE = 30;
  public static final int ENTERO = 39;
  public static final int TARGETS = 16;
  public static final int SUMAR = 23;
  public static final int BOX_COLOR = 6;
  public static final int ROWS = 3;
  public static final int CARACTER = 40;
  public static final int TYPE = 13;
  public static final int BOARD = 14;
  public static final int C_CIERRE = 32;
  public static final int COFIG = 5;
  public static final int HALL = 33;
  public static final int P_CIERRE = 28;
  public static final int HALL_COLOR = 10;
  public static final int EOF = 0;
  public static final int BRICK = 34;
  public static final int PLAYER = 17;
  public static final int COMILLAS = 21;
  public static final int SYM = 38;
  public static final int error = 1;
  public static final int COMA = 22;
  public static final int WORLD = 37;
  public static final int NAME = 2;
  public static final int COLOR = 41;
  public static final int POSY = 18;
  public static final int POSX = 19;
  public static final int COLS = 4;
  public static final int RESTAR = 24;
  public static final int DIVIDIR = 25;
  public static final int P_APERTURA = 27;
  public static final int TAGET_COLOR = 8;
  public static final int BOXES = 15;
  public static final int BOX_ON_COLOR = 7;
  public static final int ALL = 35;
  public static final int L_APERTURA = 29;
  public static final int UNDEFINED_COLOR = 11;
  public static final int PLAYER_COLOR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAME",
  "ROWS",
  "COLS",
  "COFIG",
  "BOX_COLOR",
  "BOX_ON_COLOR",
  "TAGET_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "UNDEFINED_COLOR",
  "PLAYER_COLOR",
  "TYPE",
  "BOARD",
  "BOXES",
  "TARGETS",
  "PLAYER",
  "POSY",
  "POSX",
  "DOBLE_PUNTO",
  "COMILLAS",
  "COMA",
  "SUMAR",
  "RESTAR",
  "DIVIDIR",
  "MULTIPLICAR",
  "P_APERTURA",
  "P_CIERRE",
  "L_APERTURA",
  "L_CIERRE",
  "C_APERTURA",
  "C_CIERRE",
  "HALL",
  "BRICK",
  "ALL",
  "WORLDS",
  "WORLD",
  "SYM",
  "ENTERO",
  "CARACTER",
  "COLOR"
  };
}

