
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.JFlex_Cup.HTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FINAL_UNDEFINED_COLOR = 37;
  public static final int INICIO_POSY = 24;
  public static final int INICIO_POSX = 22;
  public static final int INICIO_COLS = 10;
  public static final int FINAL_BOXES = 17;
  public static final int INICIO_PLAYER_COLOR = 38;
  public static final int ENTERO = 44;
  public static final int FINAL_TARGET_COLOR = 31;
  public static final int FINAL_PLAYER = 21;
  public static final int FINAL_HALL_COLOR = 35;
  public static final int INICIO_TARGET_COLOR = 30;
  public static final int CARACTER = 45;
  public static final int FINAL_ROWS = 9;
  public static final int INICIO_BOARD = 14;
  public static final int HALL = 43;
  public static final int INICIO_BRICK_COLOR = 32;
  public static final int FINAL_TYPE = 41;
  public static final int BRICK = 42;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int INICIO_WORLDS = 2;
  public static final int INICIO_ROWS = 8;
  public static final int FINAL_BOARD = 15;
  public static final int COLOR = 46;
  public static final int INICIO_WORLD = 4;
  public static final int INICIO_UNDEFINED_COLOR = 36;
  public static final int INICIO_TYPE = 40;
  public static final int INICIO_HALL_COLOR = 34;
  public static final int FINAL_WORLDS = 3;
  public static final int FINAL_NAME = 7;
  public static final int FINAL_POSY = 25;
  public static final int FINAL_POSX = 23;
  public static final int INICIO_CONFIG = 12;
  public static final int FINAL_COLS = 11;
  public static final int INICIO_BOX_COLOR = 26;
  public static final int INICIO_BOXES = 16;
  public static final int FINAL_BOX_COLOR_ON = 29;
  public static final int FINAL_WORLD = 5;
  public static final int FINAL_BOX_COLOR = 27;
  public static final int FINAL_PLAYER_COLOR = 39;
  public static final int FINAL_TARGETS = 19;
  public static final int INICIO_TARGETS = 18;
  public static final int FINAL_BRICK_COLOR = 33;
  public static final int INICIO_BOX_COLOR_ON = 28;
  public static final int FINAL_CONFIG = 13;
  public static final int INICIO_PLAYER = 20;
  public static final int INICIO_NAME = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO_WORLDS",
  "FINAL_WORLDS",
  "INICIO_WORLD",
  "FINAL_WORLD",
  "INICIO_NAME",
  "FINAL_NAME",
  "INICIO_ROWS",
  "FINAL_ROWS",
  "INICIO_COLS",
  "FINAL_COLS",
  "INICIO_CONFIG",
  "FINAL_CONFIG",
  "INICIO_BOARD",
  "FINAL_BOARD",
  "INICIO_BOXES",
  "FINAL_BOXES",
  "INICIO_TARGETS",
  "FINAL_TARGETS",
  "INICIO_PLAYER",
  "FINAL_PLAYER",
  "INICIO_POSX",
  "FINAL_POSX",
  "INICIO_POSY",
  "FINAL_POSY",
  "INICIO_BOX_COLOR",
  "FINAL_BOX_COLOR",
  "INICIO_BOX_COLOR_ON",
  "FINAL_BOX_COLOR_ON",
  "INICIO_TARGET_COLOR",
  "FINAL_TARGET_COLOR",
  "INICIO_BRICK_COLOR",
  "FINAL_BRICK_COLOR",
  "INICIO_HALL_COLOR",
  "FINAL_HALL_COLOR",
  "INICIO_UNDEFINED_COLOR",
  "FINAL_UNDEFINED_COLOR",
  "INICIO_PLAYER_COLOR",
  "FINAL_PLAYER_COLOR",
  "INICIO_TYPE",
  "FINAL_TYPE",
  "BRICK",
  "HALL",
  "ENTERO",
  "CARACTER",
  "COLOR"
  };
}

