package com.cunoc.Server;

public class Console extends javax.swing.JFrame {

    /**
     * Creates new form Console
     */
    public Console() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ConsoleText = new javax.swing.JTextArea() {
            private int counter = 1;
            private final String textLine = "\nLINEA : ";

            @Override
            public void append(String str) {
                String add = textLine + counter+"  "+ str;
                super.append(add);
                counter++;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Console");
        setBackground(new java.awt.Color(92, 29, 30));

        ConsoleText.setEditable(false);
        ConsoleText.setBackground(new java.awt.Color(1, 1, 1));
        ConsoleText.setColumns(20);
        ConsoleText.setFont(new java.awt.Font("Inconsolata Semi Expanded", 1, 18)); // NOI18N
        ConsoleText.setForeground(new java.awt.Color(53, 214, 233));
        ConsoleText.setRows(5);
        ConsoleText.setText("Consola:");
        ConsoleText.setDisabledTextColor(new java.awt.Color(61, 186, 200));
        ConsoleText.setSelectedTextColor(new java.awt.Color(67, 215, 222));
        ConsoleText.setSelectionColor(new java.awt.Color(186, 45, 50));
        jScrollPane1.setViewportView(ConsoleText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea ConsoleText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}